# docker-compose --version
# docker-compose: birden fazla  config, image dosyalarını çalıştırmak için kullanıyoruz.

# docker-compose version
version: '2.13.0' 

services:
 blogapp:
  container_name: spring_react_blog
  image: spring_react_blog
  restart: always
  build: ./
  ports:
   - "4444:4444"
  environment:
   - spring.datasource.url=jdbc:mysql://mysqldb:3306/blog?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
  networks:
   - springmysql
  depends_on:
   - mysqldb

 mysqldb:
  image: mysql:8.0  
  ports:
   - 3307:3306
  expose:
   - "3307"
  networks:
   - springmysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=blog
   - MYSQL_USER=hamit
   - MYSQL_PASSWORD=root
  restart: unless-stopped

networks:
  springmysql:
   name: springmysql
   driver: bridge