# docker-compose --version
# docker-compose: birden fazla  config, image dosyalarını çalıştırmak için kullanıyoruz.

# docker-compose version
version: '2.13.0' 

services:
# spring boot image
 blogapp:
  container_name: spring_react_blog
  image: spring_react_blog
  restart: always
  build: ./ # Dockerfile içindekileri çalıştır =>  docker build .
  ports:
   - "4444:4444"
  environment:
   - spring.datasource.url=jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
  networks:
   - springmysql
  depends_on:
   -mysqldb

# Mysql image
 mysqldb:
  image: mysql:8.0  #mysql:latest
  ports:
   - 3307:3306
  expose:
   - "3307"
  networks:
   - springmysql
  environment:
   -MYSQL_ROOT_PASSWORD= root
   -MYSQL_DATABASE=blog
   -MYSQL_USER=root
   -MYSQL_PASSWORD=root
  restart: unless-stopped

 # Network NOT: services aynı hizada olmalı
networks:
  springmysql:
  name: springmysql
  driver: bridge